spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      database: ${DATA_SOURCE_NAME}
      uri: ${DATA_SOURCE_URI}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true